// packages/ui-react-monitor/src/components/EngineMonitorPanel.tsx
"use client";

import React, { useCallback, useId, useMemo } from "react";
import {
  IEngine,
  IBaseSearchOptions,
  IBaseSearchInfo,
  IBaseSearchResult,
} from "@multi-game-engines/core";
import { useEngineMonitor } from "../useEngineMonitor.js";
import { EngineStats } from "./EngineStats.js";
import { PVList } from "./PVList.js";
import { SearchLog } from "./SearchLog.js";
import { ScoreBadge } from "./ScoreBadge.js";
import { EvaluationGraph } from "./EvaluationGraph.js";
import { useEngineUI } from "@multi-game-engines/ui-react-core";
import * as ScrollArea from "@radix-ui/react-scroll-area";
import * as Separator from "@radix-ui/react-separator";
import {
  Play,
  Square,
  Settings2,
  AlertCircle,
  List,
  History,
} from "lucide-react";
import { cn } from "../utils/cn.js";

interface EngineMonitorPanelProps<
  T_OPTIONS extends IBaseSearchOptions,
  T_INFO extends IBaseSearchInfo,
  T_RESULT extends IBaseSearchResult,
> {
  engine: IEngine<T_OPTIONS, T_INFO, T_RESULT>;
  searchOptions: T_OPTIONS;
  title?: string;
  className?: string;
  onMoveClick?: (move: string) => void;
}

/**
 * 思考状況を統合的に表示・制御するメインパネルコンポーネント。
 */
export function EngineMonitorPanel<
  T_OPTIONS extends IBaseSearchOptions,
  T_INFO extends IBaseSearchInfo,
  T_RESULT extends IBaseSearchResult,
>({
  engine,
  searchOptions,
  title,
  className,
  onMoveClick,
}: EngineMonitorPanelProps<T_OPTIONS, T_INFO, T_RESULT>) {
  const { strings } = useEngineUI();
  const { state, status, search, stop } = useEngineMonitor(engine);
  const [activeTab, setActiveTab] = React.useState<"pv" | "log">("pv");
  const pvTabRef = React.useRef<HTMLButtonElement>(null);
  const logTabRef = React.useRef<HTMLButtonElement>(null);
  const panelId = useId();
  const titleId = `engine-monitor-title-${panelId}`;

  const bestPV = state.pvs[0];
  const displayTitle = title ?? strings.title;

  const handleTabKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "ArrowRight" || e.key === "ArrowLeft") {
      e.preventDefault();
      const next = activeTab === "pv" ? "log" : "pv";
      setActiveTab(next);
      setTimeout(
        () => (next === "pv" ? pvTabRef : logTabRef).current?.focus(),
        0,
      );
    } else if (e.key === "Home") {
      e.preventDefault();
      setActiveTab("pv");
      setTimeout(() => pvTabRef.current?.focus(), 0);
    } else if (e.key === "End") {
      e.preventDefault();
      setActiveTab("log");
      setTimeout(() => logTabRef.current?.focus(), 0);
    }
  };

  // 2026 Best Practice: IEngine インターフェースの公式 API を使用して型安全にイベント発行
  const emitUIInteraction = useCallback(
    (action: string) => {
      engine.emitTelemetry({
        type: "lifecycle",
        timestamp: Date.now(),
        metadata: {
          component: "EngineMonitorPanel",
          action,
          engineId: engine.id,
        },
      });
    },
    [engine],
  );

  const handleStart = useCallback(() => {
    emitUIInteraction("start_click");
    void search(searchOptions);
  }, [emitUIInteraction, search, searchOptions]);

  const handleStop = useCallback(() => {
    emitUIInteraction("stop_click");
    void stop();
  }, [emitUIInteraction, stop]);

  // アクセシビリティ用：重要なステータス変更のアナウンス
  const announcement = useMemo(() => {
    if (status === "error") return strings.errorTitle;
    if (bestPV?.score.type === "mate")
      return strings.mateIn(bestPV.score.value);
    return "";
  }, [status, bestPV, strings]);

  const errorMessage = useMemo(() => {
    const err = engine.lastError;
    if (!err) return strings.errorDefaultRemediation;

    if (err.i18nKey) {
      const parts = err.i18nKey.split(".");
      const key = parts[parts.length - 1];
      const errors = strings.errors as Record<string, string> | undefined;
      if (key && errors?.[key]) {
        let msg = errors[key]!;
        if (err.i18nParams) {
          Object.entries(err.i18nParams).forEach(([k, v]) => {
            // 2026 Best Practice: プレースホルダーの全置換
            msg = msg.split(`{${k}}`).join(String(v));
          });
        }
        return msg;
      }
    }

    return err.remediation || strings.errorDefaultRemediation;
  }, [engine.lastError, strings]);

  return (
    <section
      className={cn(
        "flex flex-col h-full bg-white border border-gray-200 rounded-xl overflow-hidden shadow-lg focus-within:ring-2 focus-within:ring-blue-500/20 transition-shadow",
        className,
      )}
      aria-labelledby={titleId}
    >
      <div className="sr-only" aria-live="assertive" role="alert">
        {announcement}
      </div>

      {/* Header */}
      <header className="flex items-center justify-between px-4 py-3 bg-gray-50 border-b border-gray-200">
        <div
          className="flex items-center gap-2"
          role="status"
          aria-live="polite"
        >
          <Settings2 className="w-4 h-4 text-gray-500" aria-hidden="true" />
          <h2 id={titleId} className="font-bold text-gray-700 text-sm">
            {displayTitle}
          </h2>
          <span
            className={cn(
              "w-2 h-2 rounded-full ml-1",
              status === "busy" ? "bg-red-500 animate-pulse" : "bg-green-500",
              "motion-reduce:animate-none",
            )}
            aria-hidden="true"
          />
          <span
            className="text-[10px] text-gray-400 uppercase font-bold tracking-tight"
            role="status"
          >
            {status === "busy" ? strings.searching : strings.ready}
          </span>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={
              status === "busy" || status === "loading"
                ? handleStop
                : handleStart
            }
            className={cn(
              "group flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-bold transition-all focus:ring-2 focus:ring-offset-2 outline-none active:scale-95",
              status === "busy" || status === "loading"
                ? "bg-red-50 text-red-600 hover:bg-red-600 hover:text-white focus:ring-red-500"
                : "bg-blue-50 text-blue-600 hover:bg-blue-600 hover:text-white focus:ring-blue-500",
            )}
            aria-label={
              status === "busy" || status === "loading"
                ? strings.stop
                : strings.start
            }
          >
            {status === "busy" || status === "loading" ? (
              <Square className="w-3 h-3 fill-current" />
            ) : (
              <Play className="w-3 h-3 fill-current" />
            )}
            <span className="hidden sm:inline">
              {status === "busy" || status === "loading"
                ? strings.stop
                : strings.start}
            </span>
          </button>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex-1 flex flex-col min-h-0">
        {status === "error" ? (
          <div className="flex-1 flex flex-col items-center justify-center p-8 text-center text-red-500 bg-red-50/30">
            <AlertCircle className="w-12 h-12 mb-4 animate-bounce motion-reduce:animate-none" />
            <h3 className="font-bold mb-1">{strings.errorTitle}</h3>
            <p className="text-xs text-red-400 max-w-[240px]">{errorMessage}</p>
          </div>
        ) : (
          <>
            <section className="p-4 bg-gradient-to-br from-white to-gray-50/50">
              <div className="flex items-center justify-between mb-2">
                <span className="text-[10px] text-gray-400 font-black uppercase tracking-widest">
                  {strings.topCandidate}
                </span>
                {bestPV && (
                  <ScoreBadge
                    score={bestPV.score}
                    className="scale-110 origin-right"
                  />
                )}
              </div>
              <div className="text-xl font-mono font-black text-gray-900 truncate leading-tight tracking-tighter">
                {bestPV?.moves[0]?.toString() || strings.noMove}
              </div>
            </section>

            {/* Evaluation Trend Graph */}
            <div className="px-4 py-2 bg-white">
              <EvaluationGraph
                entries={state.evaluationHistory.entries}
                height={40}
                className="opacity-80 hover:opacity-100 transition-opacity"
              />
            </div>

            <Separator.Root className="h-[1px] bg-gray-100" />

            <EngineStats
              stats={state.stats}
              className="rounded-none bg-white border-none py-3"
            />

            <Separator.Root className="h-[1px] bg-gray-100" />

            <div className="flex-1 min-h-0 flex flex-col">
              <div className="px-4 py-2 bg-gray-50/50 flex items-center justify-between border-b border-gray-100">
                <div
                  className="flex items-center gap-4"
                  role="tablist"
                  aria-orientation="horizontal"
                  onKeyDown={handleTabKeyDown}
                >
                  <button
                    ref={pvTabRef}
                    onClick={() => setActiveTab("pv")}
                    role="tab"
                    aria-selected={activeTab === "pv"}
                    aria-controls={`${panelId}-pv-panel`}
                    id={`${panelId}-pv-tab`}
                    tabIndex={activeTab === "pv" ? 0 : -1}
                    className={cn(
                      "flex items-center gap-1 text-[10px] font-black uppercase tracking-widest transition-colors outline-none",
                      activeTab === "pv"
                        ? "text-blue-600"
                        : "text-gray-400 hover:text-gray-600",
                    )}
                  >
                    <List className="w-3 h-3" />
                    {strings.principalVariations}
                  </button>
                  <button
                    ref={logTabRef}
                    onClick={() => setActiveTab("log")}
                    role="tab"
                    aria-selected={activeTab === "log"}
                    aria-controls={`${panelId}-log-panel`}
                    id={`${panelId}-log-tab`}
                    tabIndex={activeTab === "log" ? 0 : -1}
                    className={cn(
                      "flex items-center gap-1 text-[10px] font-black uppercase tracking-widest transition-colors outline-none",
                      activeTab === "log"
                        ? "text-blue-600"
                        : "text-gray-400 hover:text-gray-600",
                    )}
                  >
                    <History className="w-3 h-3" />
                    {strings.searchLog}
                  </button>
                </div>
                <span className="text-[10px] font-mono text-gray-300">
                  {activeTab === "pv"
                    ? strings.pvCount(state.pvs.length)
                    : strings.logCount(state.searchLog.length)}
                </span>
              </div>
              <ScrollArea.Root className="flex-1 overflow-hidden">
                <ScrollArea.Viewport className="h-full w-full p-4">
                  <div
                    role="tabpanel"
                    id={`${panelId}-pv-panel`}
                    aria-labelledby={`${panelId}-pv-tab`}
                    className="h-full"
                    hidden={activeTab !== "pv"}
                  >
                    <PVList pvs={state.pvs} onMoveClick={onMoveClick} />
                  </div>
                  <div
                    role="tabpanel"
                    id={`${panelId}-log-panel`}
                    aria-labelledby={`${panelId}-log-tab`}
                    className="h-full"
                    hidden={activeTab !== "log"}
                  >
                    <SearchLog
                      log={state.searchLog}
                      onMoveClick={onMoveClick}
                    />
                  </div>
                </ScrollArea.Viewport>
                <ScrollArea.Scrollbar
                  className="flex select-none touch-none p-0.5 bg-gray-100/50 transition-colors duration-150 ease-out hover:bg-gray-200 data-[orientation=vertical]:w-2"
                  orientation="vertical"
                >
                  <ScrollArea.Thumb className="flex-1 bg-gray-300 rounded-full relative" />
                </ScrollArea.Scrollbar>
              </ScrollArea.Root>
            </div>
          </>
        )}
      </div>

      <footer className="px-4 py-2 bg-gray-50/80 border-t border-gray-200 text-[9px] text-gray-400 flex justify-between font-medium">
        <span className="truncate mr-4">
          {strings.engineVersion(engine.name, engine.version)}
        </span>
        <span className="flex-shrink-0">
          {strings.engineBridgeStandard(2026)}
        </span>
      </footer>
    </section>
  );
}

// packages/ui-vue-monitor/src/EngineMonitorPanel.vue
<script
  setup
  lang="ts"
  generic="
    T_OPTIONS extends IBaseSearchOptions,
    T_INFO extends ExtendedSearchInfo,
    T_RESULT extends IBaseSearchResult
  "
>
import { computed, ref, nextTick, useId } from "vue";
import {
  IEngine,
  IBaseSearchOptions,
  IBaseSearchResult,
} from "@multi-game-engines/core";
import {
  EngineSearchState,
  ExtendedSearchInfo,
} from "@multi-game-engines/ui-core";
import { useEngineMonitor } from "./useEngineMonitor.js";
import { useEngineUI } from "@multi-game-engines/ui-vue-core";
import ScoreBadge from "./ScoreBadge.vue";
import EngineStats from "./EngineStats.vue";
import EvaluationGraph from "./EvaluationGraph.vue";
import PVList from "./PVList.vue";
import SearchLog from "./SearchLog.vue";
import {
  Settings2,
  Play,
  Square,
  AlertCircle,
  ScrollText,
  History,
} from "lucide-vue-next";

// 2026 Best Practice: Vue 3.3+ のジェネリック・マクロを使用
const props = defineProps<{
  engine: IEngine<T_OPTIONS, T_INFO, T_RESULT>;
  searchOptions: T_OPTIONS;
  title?: string | undefined;
}>();

const emit = defineEmits<{
  (e: "moveClick", move: string): void;
}>();

const panelId = useId();
const titleId = `engine-monitor-title-${panelId}`;

const { strings } = useEngineUI();
const activeTab = ref<"pv" | "log">("pv");
const pvTabRef = ref<HTMLButtonElement | null>(null);
const logTabRef = ref<HTMLButtonElement | null>(null);

const emitUIInteraction = (action: string) => {
  props.engine.emitTelemetry({
    type: "lifecycle",
    timestamp: Date.now(),
    metadata: {
      component: "EngineMonitorPanel",
      action,
      engineId: props.engine.id,
    },
  });
};

const handleTabKeyDown = (e: KeyboardEvent) => {
  if (e.key === "ArrowRight" || e.key === "ArrowLeft") {
    e.preventDefault();
    activeTab.value = activeTab.value === "pv" ? "log" : "pv";
    focusTab();
  } else if (e.key === "Home") {
    e.preventDefault();
    activeTab.value = "pv";
    focusTab();
  } else if (e.key === "End") {
    e.preventDefault();
    activeTab.value = "log";
    focusTab();
  }
};

const focusTab = () => {
  nextTick(() => {
    if (activeTab.value === "pv") pvTabRef.value?.focus();
    else logTabRef.value?.focus();
  });
};

const { state, status, search, stop } = useEngineMonitor<
  EngineSearchState,
  T_OPTIONS,
  T_INFO,
  T_RESULT
>(() => props.engine, {
  autoMiddleware: true,
});

const bestPV = computed(() => state.value.pvs[0]);
const displayTitle = computed(() => props.title ?? strings.value.title);

const announcement = computed(() => {
  if (status.value === "error") return strings.value.errorTitle;
  if (bestPV.value?.score.type === "mate")
    return strings.value.mateIn(bestPV.value.score.value);
  return "";
});

const handleStart = async () => {
  emitUIInteraction("start_click");
  void search(props.searchOptions);
};

const handleStop = async () => {
  emitUIInteraction("stop_click");
  void stop();
};

const handleMoveClick = (move: string) => {
  emit("moveClick", move);
};

const errorMessage = computed(() => {
  const err = props.engine.lastError;
  if (!err) return strings.value.errorDefaultRemediation;

  if (err.i18nKey) {
    // 2026 Best Practice: i18n リソースからの動的取得
    const parts = err.i18nKey.split(".");
    const key = parts[parts.length - 1];
    const errors = strings.value.errors as Record<string, string> | undefined;
    if (key && errors?.[key]) {
      let msg = errors[key]!;
      // パラメータ置換 (例: {move} -> "7g7f")
      if (err.i18nParams) {
        Object.entries(err.i18nParams).forEach(([k, v]) => {
          msg = msg.split(`{${k}}`).join(String(v));
        });
      }
      return msg;
    }
  }

  return err.remediation || strings.value.errorDefaultRemediation;
});
</script>

<template>
  <section
    class="flex flex-col h-full bg-white border border-gray-200 rounded-xl overflow-hidden shadow-lg transition-all hover:shadow-xl"
    :aria-labelledby="titleId"
  >
    <div class="sr-only" aria-live="assertive" role="alert">
      {{ announcement }}
    </div>
    <!-- Header -->
    <header
      class="flex items-center justify-between px-4 py-3 bg-gray-50 border-b border-gray-200"
    >
      <div class="flex items-center gap-2">
        <Settings2 class="w-4 h-4 text-gray-500" />
        <h2
          :id="titleId"
          class="font-bold text-gray-700 text-sm tracking-tight"
        >
          {{ displayTitle }}
        </h2>
        <span
          :class="[
            'w-2.5 h-2.5 rounded-full ml-1 ring-2 ring-white shadow-sm transition-colors duration-500',
            status === 'busy' ? 'bg-green-500 animate-pulse' : 'bg-gray-300',
          ]"
          :title="status"
        />
        <span class="text-[10px] text-gray-400 uppercase font-bold tracking-tight">
          {{ status === 'busy' ? strings.searching : strings.ready }}
        </span>
      </div>

      <div class="flex items-center gap-2">
        <button
          v-if="status === 'busy' || status === 'loading'"
          @click="handleStop"
          type="button"
          class="flex items-center gap-1.5 px-3 py-1.5 bg-red-50 text-red-600 rounded-lg text-xs font-bold hover:bg-red-100 active:scale-95 transition-all focus:ring-2 focus:ring-red-200 outline-none"
        >
          <Square class="w-3.5 h-3.5 fill-current" />
          {{ strings.stop }}
        </button>
        <button
          v-else
          @click="handleStart"
          type="button"
          class="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 text-white rounded-lg text-xs font-bold hover:bg-blue-700 active:scale-95 transition-all shadow-md shadow-blue-200 focus:ring-2 focus:ring-blue-300 outline-none"
        >
          <Play class="w-3.5 h-3.5 fill-current" />
          {{ strings.start }}
        </button>
      </div>
    </header>

    <!-- Content Area -->
    <div class="flex-1 flex flex-col min-h-0 bg-white">
      <!-- Error State -->
      <div
        v-if="status === 'error'"
        class="flex-1 flex flex-col items-center justify-center p-8 text-center text-red-500 animate-in fade-in zoom-in duration-300"
        role="alert"
      >
        <div class="p-4 bg-red-50 rounded-full mb-4">
          <AlertCircle class="w-10 h-10" />
        </div>
        <h3 class="font-bold text-lg mb-1">{{ strings.errorTitle }}</h3>
        <p class="text-sm text-gray-600 max-w-[240px] leading-relaxed">
          {{ errorMessage }}
        </p>
      </div>

      <template v-else>
        <!-- Best Move & Score Summary -->
        <section
          class="p-5 border-b border-gray-100 bg-gradient-to-br from-white to-gray-50/50"
          aria-label="Current Best Analysis"
        >
          <div class="flex items-center justify-between mb-3">
            <span
              class="text-[10px] text-gray-400 font-extrabold uppercase tracking-widest"
              >{{ strings.topCandidate }}</span
            >
            <ScoreBadge
              v-if="bestPV"
              :score="bestPV.score"
              class="scale-110 shadow-sm"
            />
          </div>
          <div class="flex items-baseline gap-3">
            <div
              class="text-3xl font-mono font-black text-gray-900 tracking-tighter"
            >
              {{ bestPV?.moves[0] || strings.noMove }}
            </div>
            <div
              v-if="state.currentMove"
              class="text-sm text-gray-400 font-mono"
            >
              (evaluating {{ state.currentMove }})
            </div>
          </div>
        </section>

        <!-- Evaluation Trend Graph -->
        <div class="px-4 py-2 bg-white">
          <EvaluationGraph
            :entries="state.evaluationHistory.entries"
            :height="40"
            class="opacity-80 hover:opacity-100 transition-opacity"
          />
        </div>

        <!-- Stats Infrastructure -->
        <EngineStats :stats="state.stats" class="border-b border-gray-100" />

        <!-- Principal Variations / Log List -->
        <div class="flex-1 flex flex-col min-h-0">
          <div
            class="px-4 py-2 bg-gray-50/50 border-b border-gray-100 flex items-center justify-between"
          >
            <div
              class="flex items-center gap-4"
              role="tablist"
              aria-orientation="horizontal"
              @keydown="handleTabKeyDown"
            >
              <button
                ref="pvTabRef"
                @click="activeTab = 'pv'"
                role="tab"
                :aria-selected="activeTab === 'pv'"
                :aria-controls="`${panelId}-pv-panel`"
                :id="`${panelId}-pv-tab`"
                :tabindex="activeTab === 'pv' ? 0 : -1"
                class="flex items-center gap-1.5 transition-colors outline-none"
                :class="activeTab === 'pv' ? 'text-blue-600' : 'text-gray-400 hover:text-gray-600'"
              >
                <ScrollText class="w-3.5 h-3.5" />
                <span class="text-[10px] font-bold uppercase tracking-wider">{{ strings.principalVariations }}</span>
              </button>
              <button
                ref="logTabRef"
                @click="activeTab = 'log'"
                role="tab"
                :aria-selected="activeTab === 'log'"
                :aria-controls="`${panelId}-log-panel`"
                :id="`${panelId}-log-tab`"
                :tabindex="activeTab === 'log' ? 0 : -1"
                class="flex items-center gap-1.5 transition-colors outline-none"
                :class="activeTab === 'log' ? 'text-blue-600' : 'text-gray-400 hover:text-gray-600'"
              >
                <History class="w-3.5 h-3.5" />
                <span class="text-[10px] font-bold uppercase tracking-wider">{{ strings.searchLog }}</span>
              </button>
            </div>
            <span class="text-[10px] font-mono text-gray-300">
              {{ activeTab === 'pv' ? strings.pvCount(state.pvs.length) : strings.logCount(state.searchLog.length) }}
            </span>
          </div>
          <div class="flex-1 overflow-y-auto custom-scrollbar">
            <div
              role="tabpanel"
              :id="`${panelId}-pv-panel`"
              :aria-labelledby="`${panelId}-pv-tab`"
              :hidden="activeTab !== 'pv'"
              class="h-full"
            >
              <PVList
                v-if="activeTab === 'pv'"
                :pvs="state.pvs"
                class="p-4"
                @move-click="handleMoveClick"
              />
            </div>
            <div
              role="tabpanel"
              :id="`${panelId}-log-panel`"
              :aria-labelledby="`${panelId}-log-tab`"
              :hidden="activeTab !== 'log'"
              class="h-full"
            >
              <SearchLog
                v-if="activeTab === 'log'"
                :log="state.searchLog"
                class="border-none rounded-none"
                @move-click="handleMoveClick"
              />
            </div>
          </div>
        </div>
      </template>
    </div>

    <!-- Footer -->
    <footer
      class="px-4 py-2 bg-gray-50/80 border-t border-gray-200 text-[9px] text-gray-400 flex justify-between font-medium"
    >
      <span class="truncate mr-4">
        {{ strings.engineVersion(engine.name, engine.version) }}
      </span>
      <span class="flex-shrink-0">
        {{ strings.engineBridgeStandard(2026) }}
      </span>
    </footer>
  </section>
</template>

<style scoped>
.custom-scrollbar::-webkit-scrollbar {
  width: 6px;
}
.custom-scrollbar::-webkit-scrollbar-track {
  background: transparent;
}
.custom-scrollbar::-webkit-scrollbar-thumb {
  background: #e5e7eb;
  border-radius: 3px;
}
.custom-scrollbar::-webkit-scrollbar-thumb:hover {
  background: #d1d5db;
}
</style>
