// packages/ui-react/src/EvaluationGraph.tsx
"use client";

import React, { useMemo } from "react";
import {
  EvaluationPresenter,
  IEvaluationHistoryEntry,
} from "@multi-game-engines/ui-core";
import { useEngineUI } from "./EngineUIProvider.js";

interface EvaluationGraphProps {
  entries: IEvaluationHistoryEntry[];
  width?: number | string;
  height?: number;
  className?: string;
}

/**
 * 評価値の推移を視覚化するグラフコンポーネント。
 */
export const EvaluationGraph: React.FC<EvaluationGraphProps> = ({
  entries,
  width = "100%",
  height = 60,
  className = "",
}) => {
  const { strings } = useEngineUI();
  const points = useMemo(() => {
    // 内部的な計算用に固定幅 200 を使用し、SVG の preserveAspectRatio でリサイズ対応
    return EvaluationPresenter.getGraphPoints(entries, 200, height);
  }, [entries, height]);

  const pathData = useMemo(() => {
    if (points.length < 2) return "";
    return `M ${points.map((p) => `${p.x},${p.y}`).join(" L ")}`;
  }, [points]);

  return (
    <div
      className={`relative overflow-hidden rounded bg-gray-50/50 p-1 ${className}`}
      style={{ width, height }}
      aria-label={strings.evaluationGraph}
      role="img"
    >
      <svg
        viewBox={`0 0 200 ${height}`}
        className="h-full w-full overflow-visible"
        preserveAspectRatio="none"
      >
        {/* ゼロライン */}
        <line
          x1="0"
          y1={height / 2}
          x2="200"
          y2={height / 2}
          stroke="currentColor"
          className="text-gray-200"
          strokeDasharray="2,2"
        />

        {/* 推移ライン */}
        <path
          d={pathData}
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="text-primary transition-all duration-300 ease-in-out"
        />

        {/* 最新のポイント */}
        {points.length > 0 && points[points.length - 1] && (
          <circle
            cx={points[points.length - 1]!.x}
            cy={points[points.length - 1]!.y}
            r="3"
            className="fill-primary"
          />
        )}
      </svg>
    </div>
  );
};

// packages/ui-vue-monitor/src/EvaluationGraph.vue
<script setup lang="ts">
import { computed } from 'vue';
import { EvaluationPresenter, IEvaluationHistoryEntry } from '@multi-game-engines/ui-core';
import { useEngineUI } from '@multi-game-engines/ui-vue-core';

interface Props {
  entries: IEvaluationHistoryEntry[];
  width?: number | string;
  height?: number;
}

const props = withDefaults(defineProps<Props>(), {
  width: '100%',
  height: 60
});

const { strings } = useEngineUI();

const points = computed(() => {
  return EvaluationPresenter.getGraphPoints(props.entries, 200, props.height);
});

const pathData = computed(() => {
  if (points.value.length < 2) return '';
  return `M ${points.value.map((p) => `${p.x},${p.y}`).join(' L ')}`;
});

const lastPoint = computed(() => {
  return points.value.length > 0 ? points.value[points.value.length - 1] : null;
});
</script>

<template>
  <div
    class="relative overflow-hidden rounded bg-gray-50/50 p-1"
    :style="{ width: typeof width === 'number' ? `${width}px` : width, height: `${height}px` }"
    :aria-label="strings.evaluationGraph"
    role="img"
  >
    <svg
      :viewBox="`0 0 200 ${props.height}`"
      class="h-full w-full overflow-visible"
      preserveAspectRatio="none"
    >
      <!-- ゼロライン -->
      <line
        x1="0"
        :y1="props.height / 2"
        x2="200"
        :y2="props.height / 2"
        stroke="currentColor"
        class="text-gray-200"
        stroke-dasharray="2,2"
      />

      <!-- 推移ライン -->
      <path
        :d="pathData"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        class="text-primary transition-all duration-300 ease-in-out"
      />

      <!-- 最新のポイント -->
      <circle
        v-if="lastPoint"
        :cx="lastPoint.x"
        :cy="lastPoint.y"
        r="3"
        class="fill-primary"
      />
    </svg>
  </div>
</template>
