// packages/ui-react-monitor/src/components/PVList.tsx
import React, { memo } from "react";
import { PrincipalVariation } from "@multi-game-engines/ui-core";
import { ScoreBadge } from "./ScoreBadge.js";
import { useEngineUI } from "@multi-game-engines/ui-react-core";
import { cn } from "../utils/cn.js";

export interface PVListProps {
  pvs: PrincipalVariation[];
  onMoveClick?:
    | ((move: string, index: number, pv: PrincipalVariation) => void)
    | undefined;
  className?: string | undefined;
}

/**
 * エンジンの読み筋（Principal Variations）を一覧表示するコンポーネント。
 */
export const PVList: React.FC<PVListProps> = memo(
  ({ pvs, onMoveClick, className }) => {
    const { strings } = useEngineUI();

    return (
      <div className={cn("space-y-2", className)}>
        {pvs.map((pv) => (
          <div
            key={pv.multipv}
            className="flex flex-col p-3 bg-white border border-gray-200 rounded-lg shadow-sm hover:border-blue-300 transition-colors"
          >
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <span className="text-xs font-bold text-gray-400">
                  #{pv.multipv}
                </span>
                <ScoreBadge score={pv.score} />
              </div>
            </div>

            <div className="flex flex-wrap gap-1 font-mono text-sm leading-relaxed">
              {pv.moves.map((move, idx) => (
                <button
                  key={`${pv.multipv}-${move}`}
                  onClick={() => onMoveClick?.(move.toString(), idx, pv)}
                  className={cn(
                    "px-1 rounded hover:bg-blue-100 hover:text-blue-700 transition-colors cursor-pointer focus:outline-none focus:ring-2 focus:ring-blue-500",
                    idx === 0 ? "font-bold text-gray-900" : "text-gray-600",
                  )}
                  aria-label={strings.moveAriaLabel(move.toString())}
                >
                  {move.toString()}
                </button>
              ))}
            </div>
          </div>
        ))}

        {pvs.length === 0 && (
          <div className="py-8 text-center text-gray-400 italic text-sm">
            {strings.searching}
          </div>
        )}
      </div>
    );
  },
);

// packages/ui-vue-monitor/src/components/PVList.vue
<script setup lang="ts">
import { PrincipalVariation } from "@multi-game-engines/ui-core";
import ScoreBadge from "./ScoreBadge.vue";
import { useEngineUI } from "@multi-game-engines/ui-vue-core";

interface Props {
  pvs: PrincipalVariation[];
  className?: string;
}

const props = withDefaults(defineProps<Props>(), {
  className: "",
});

const emit = defineEmits<{
  (e: "move-click", move: string, index: number, pv: PrincipalVariation): void;
}>();

const { strings } = useEngineUI();
</script>

<template>
  <div :class="['space-y-2', className]">
    <div
      v-for="pv in pvs"
      :key="pv.multipv"
      class="flex flex-col p-3 bg-white border border-gray-200 rounded-lg shadow-sm hover:border-blue-300 transition-colors"
    >
      <div class="flex items-center justify-between mb-2">
        <div class="flex items-center gap-2">
          <span class="text-xs font-bold text-gray-400">
            #{{ pv.multipv }}
          </span>
          <ScoreBadge :score="pv.score" />
        </div>
      </div>

      <div class="flex flex-wrap gap-1 font-mono text-sm leading-relaxed">
        <button
          v-for="(move, idx) in pv.moves"
          :key="`${pv.multipv}-${idx}-${move}`"
          type="button"
          @click="emit('move-click', move.toString(), idx, pv)"
          class="px-1 rounded hover:bg-blue-100 hover:text-blue-700 transition-colors cursor-pointer focus:outline-none focus:ring-2 focus:ring-blue-500"
          :class="idx === 0 ? 'font-bold text-gray-900' : 'text-gray-600'"
          :aria-label="strings.moveAriaLabel(move.toString())"
        >
          {{ move.toString() }}
        </button>
      </div>
    </div>

    <div
      v-if="pvs.length === 0"
      class="py-8 text-center text-gray-400 italic text-sm"
    >
      {{ strings.searching }}
    </div>
  </div>
</template>
